### ISSUE TITLE
Rename config property to "alertmanager-url"

### ISSUE THREAD

**Issue by mmanciop** [xavpaice/charm-alertmanager-karma-proxy#1]
We need that to be resolvable, so it is not a URI, it's a URL :-)

https://github.com/xavpaice/charm-alertmanager-karma-proxy/blob/9f1f81b720b4a110a2d3d9aeb0a2bc6ad728dff3/config.yaml#L6

**Comment by xavpaice** [comment]
Fixed in https://github.com/xavpaice/charm-alertmanager-karma-proxy/commit/3d89fb9b694b5d775d1f79603fd71b7d1469c3ed
